// (c) Clayground Contributors - MIT License, see "LICENSE" file
.pragma library

// Every user-visible string of Character 101, EN and DE, from the first
// commit. The two blocks must carry the SAME KEYS - a missing German key
// shows the raw key on screen. The kit's vocabulary (gestures, moves, faces,
// builds, readings) lives in labs/kits/character/strings.js; what is here is
// the lab's own: the scenarios, what each aspect is for, the hints, the keys
// and the tour. Key letters are physical and never translated.
var dict = {
    "en": {
        "lab.title": "CHARACTER 101",

        "scenario.lineup": "lineup",
        "scenario.gait": "gait",
        "scenario.gestures": "gestures",
        "scenario.action": "action",
        "scenario.moves": "moves",
        "scenario.hands": "hands",
        "scenario.faces": "faces",
        "scenario.heads": "heads",
        "scenario.speech": "speech",
        "scenario.conversation": "conversation",
        "scenario.crowd": "crowd",

        "scenario.note.lineup": "six builds walk the same cycle — the build sets the tempo, not the animator",
        "scenario.note.gait": "one cycle frozen at eight phases: contacts and passing positions on one sheet",
        "scenario.note.gestures": "every gesture side by side, nothing moving — the set is what is judged",
        "scenario.note.action": "working and boxing, live, from the clock — a punch that floats freezes like one that snaps",
        "scenario.note.moves": "a loadable move set, one frozen figure per move — is each one the thing its name says?",
        "scenario.note.hands": "the plain hand and the articulated one, same pose, same light — close up and from across the room",
        "scenario.note.faces": "the six expressions, same head, same angle — distinguishable is a claim about the set",
        "scenario.note.heads": "three detail tiers of one head — a tier swap has to be invisible",
        "scenario.note.speech": "one recording, three lip-sync tiers — what each one can and cannot hear",
        "scenario.note.conversation": "one speaks, the other listens or does not — attention is mostly the eyes",
        "scenario.note.crowd": "how many characters this machine affords, and why draws matter and vertices do not",

        "aspect.lineup.for": "The claim the plugin makes about itself: one procedural walk, every body. The child's cycle is shorter and quicker than the heavy figure's because the gait model derives tempo and stride from the build.",
        "aspect.gait.for": "A walk is checked on a sheet, not in motion. The record holds the cycle length, the speed the feet ask for, and the hip, knee, arm and lift curves the clock walks through.",
        "aspect.gestures.for": "Can a stranger name each gesture from the silhouette alone? Press S. The aimed ones ran the real solver; the boxing and working columns are frozen phases of the action cycles.",
        "aspect.action.for": "The two whole-body actions, running. Pause the clock and step it to judge a frame; the readings measure the fists against the shoulders and the chin in head heights.",
        "aspect.moves.for": "What a character KNOWS rather than what it is: a move set, loaded on demand. The lowest foot must stay on the floor and a front kick must clear the hip — both are numbers here.",
        "aspect.hands.for": "A hand is judged from two distances at once: close up it has to be a hand, from across the room only its outline survives. The readings say how big it lands on screen.",
        "aspect.faces.for": "An expression is ten shader uniforms. The readings print them and the closest pair says how distinct the set is — a face judged alone is judged against a memory.",
        "aspect.heads.for": "The face is drawn in a shader, so the cheap tiers can thin it instead of deleting it. The head's height in pixels is the number a tier swap is judged at.",
        "aspect.speech.for": "The envelope tier cannot tell oo from ee; the spectral one can; the aligned one needs a transcript nobody wrote for these two recordings, and says so.",
        "aspect.conversation.for": "The half of a conversation nobody was animating. Turn listening off and the same body is just standing there while someone talks at it.",
        "aspect.crowd.for": "Render cost is a count of boxes: draw calls, not vertices. Every character is twenty-two boxes at Low and forty-four with fingers, on any machine.",

        "shot.front": "front",
        "shot.quarter": "three-quarter",
        "shot.side": "side",
        "shot.back": "back",
        "shot.top": "top",
        "shot.face": "face",
        "shot.profile": "profile",
        "shot.work": "working distance",
        "shot.far": "far",
        "shot.hand": "hand",
        "shot.palm": "palm",
        "shot.arm": "arm",
        "shot.hands": "the hands",
        "shot.close": "close",
        "shot.over": "over the shoulder",

        "key.readout": "the aspect card",
        "key.plot": "the plot",
        "key.silhouette": "silhouette",
        "key.shot": "next shot",

        "plot.empty": "nothing to plot in this scene",
        "banner.posing": "posing the figures…",

        "hint.idle": "1-9 pick an aspect · T for the tour · right-drag turns · wheel zooms",
        "hint.lineup": "walk or run on the card · N turns the row · pause the clock to compare a frame",
        "hint.gait": "preset and emotion on the card · N cycles side, front, back, top · frames on the right",
        "hint.gestures": "S strips it to a silhouette · N turns the sheet · pick a column to enlarge it",
        "hint.action": "boxing or working on the card · pause and step the clock to freeze a frame",
        "hint.moves": "pick a move to see it as a strip of phases · N turns the sheet",
        "hint.hands": "poses and arm on the card · N steps through the close-ups · S for the outline",
        "hint.faces": "pick one expression to fill the frame · N for the profile",
        "hint.heads": "pick the subject and what it does · N walks the distances",
        "hint.speech": "play a recording on the card · the three mouths read the same file",
        "hint.conversation": "say a line on the card · L toggles listening · swap the speaker",
        "hint.crowd": "characters and detail on the right · close other GPU work before reading a millisecond",

        "flow.character-tour.title": "how a character is put together",
        "flow.character-tour.lineup": "Six bodies from the parametric character's slider space, all walking one cycle. Nothing was animated per body: the gait model derives each figure's tempo and stride from its build.",
        "flow.character-tour.gait": "A walk is judged on a sheet. This is the elderly preset frozen at eight phases: t = 0 and 0.5 are the contacts, 0.25 and 0.75 the passing positions. Its cycle takes 1.11 s.",
        "flow.character-tour.gaitTop": "From above, the sway and the rock are the only things you can see — which is why a sheet is read from four angles before a gait is called done.",
        "flow.character-tour.try": "Your turn: switch the cycle to a run and watch the sheet re-pose. The record's cycle length changes with it.",
        "flow.character-tour.try.hint": "the cycle chips are on the aspect card, top-left",
        "flow.character-tour.run": "The same preset over the run base: 0.63 s a cycle. A gait is a base times a factor vector, and both are numbers a record holds.",
        "flow.character-tour.gestures": "The arms next. Thirteen columns, nothing moving: three hand shapes, three aimed gestures through the real solver, and five frozen phases of the two action cycles. The set is what is judged.",
        "flow.character-tour.silhouette": "Press S, or wait: one ink, no light. Can a stranger still name each column? A gesture that needs shading to read will not survive a wide shot.",
        "flow.character-tour.action": "The boxing loop, running from the lab's clock — 1.70 s a round at half intensity. Pause the clock and step it: a punch that floats and one that snaps freeze to the same picture, so motion is judged here.",
        "flow.character-tour.moves": "What a character knows rather than what it is: a martial-arts set of fourteen moves, loaded on demand. The lowest foot stays on the floor — a number, not an impression.",
        "flow.character-tour.hands": "Closer. The articulated hand beside the plain box, same pose, same light. Its palm is 1.10 arm widths across on this build, and the readings say how many pixels it lands on.",
        "flow.character-tour.faces": "The six expressions on one head. Each is ten shader uniforms; the closest pair of the six is 1.206 apart in that space, which is what makes distinguishable a number.",
        "flow.character-tour.heads": "Three detail tiers of the same head at the working distance, talking. The face is a shader, so the cheap tiers thin it instead of deleting it — the head's pixel height is the number a swap is judged at.",
        "flow.character-tour.speech": "The voice: one recording, three lip-sync tiers. The envelope tier cannot tell oo from ee, the spectral one can, and the aligned one wants a transcript nobody wrote.",
        "flow.character-tour.conversation": "The half of a conversation nobody was animating: a listener. Turn listening off on the card and the same body just stands there while someone talks at it.",
        "flow.character-tour.crowd": "What it all costs. Twenty characters at Low are 440 boxes, and a box is a draw call; vertices barely matter. Every number here is this machine's — the shape of the result is what carries.",
        "flow.character-tour.handoff": "That is the whole character: a body, a walk, the arms, the face, a voice, a crowd — one procedural model, and every aspect a scenario you can measure. Pick one and read its card."
    },
    "de": {
        "lab.title": "CHARACTER 101",

        "scenario.lineup": "Aufstellung",
        "scenario.gait": "Gang",
        "scenario.gestures": "Gesten",
        "scenario.action": "Tätigkeit",
        "scenario.moves": "Techniken",
        "scenario.hands": "Hände",
        "scenario.faces": "Gesichter",
        "scenario.heads": "Köpfe",
        "scenario.speech": "Sprache",
        "scenario.conversation": "Gespräch",
        "scenario.crowd": "Menge",

        "scenario.note.lineup": "sechs Körperbauten gehen denselben Zyklus — der Körperbau setzt das Tempo, nicht der Animator",
        "scenario.note.gait": "ein Zyklus, in acht Phasen eingefroren: Kontakte und Durchgänge auf einem Bogen",
        "scenario.note.gestures": "jede Geste nebeneinander, nichts bewegt sich — beurteilt wird der Satz",
        "scenario.note.action": "Arbeiten und Boxen, live von der Uhr — ein Schlag, der schwebt, friert ein wie einer, der sitzt",
        "scenario.note.moves": "ein ladbarer Techniksatz, eine eingefrorene Figur je Technik — ist jede das, was ihr Name sagt?",
        "scenario.note.hands": "die einfache und die gegliederte Hand, gleiche Haltung, gleiches Licht — nah und quer durch den Raum",
        "scenario.note.faces": "die sechs Ausdrücke, gleicher Kopf, gleicher Winkel — unterscheidbar ist eine Aussage über den Satz",
        "scenario.note.heads": "drei Detailstufen eines Kopfes — ein Stufenwechsel muss unsichtbar sein",
        "scenario.note.speech": "eine Aufnahme, drei Lippensynchron-Stufen — was jede hören kann und was nicht",
        "scenario.note.conversation": "einer spricht, der andere hört zu oder nicht — Aufmerksamkeit sind vor allem die Augen",
        "scenario.note.crowd": "wie viele Figuren diese Maschine sich leisten kann, und warum Zeichenaufrufe zählen und Eckpunkte nicht",

        "aspect.lineup.for": "Der Anspruch, den das Plugin an sich stellt: ein prozeduraler Gang, jeder Körper. Der Zyklus des Kindes ist kürzer und schneller als der der schweren Figur, weil das Gangmodell Tempo und Schrittlänge aus dem Körperbau ableitet.",
        "aspect.gait.for": "Ein Gang wird auf einem Bogen geprüft, nicht in Bewegung. Die Aufzeichnung enthält Zykluslänge, das Tempo, das die Füße verlangen, und die Kurven von Hüfte, Knie, Arm und Hub, die die Uhr durchläuft.",
        "aspect.gestures.for": "Kann ein Fremder jede Geste allein an der Silhouette benennen? S drücken. Die gezielten liefen durch den echten Löser; die Box- und Arbeitsspalten sind eingefrorene Phasen der Tätigkeitszyklen.",
        "aspect.action.for": "Die zwei Ganzkörper-Tätigkeiten, laufend. Uhr anhalten und schrittweise vorrücken, um ein Bild zu beurteilen; die Messwerte setzen die Fäuste in Kopfhöhen zu Schultern und Kinn ins Verhältnis.",
        "aspect.moves.for": "Was eine Figur KANN, nicht was sie ist: ein Techniksatz, bei Bedarf geladen. Der tiefste Fuß muss am Boden bleiben und ein Fronttritt über die Hüfte — beides sind hier Zahlen.",
        "aspect.hands.for": "Eine Hand wird aus zwei Entfernungen zugleich beurteilt: nah muss sie eine Hand sein, quer durch den Raum überlebt nur ihr Umriss. Die Messwerte sagen, wie groß sie am Bildschirm landet.",
        "aspect.faces.for": "Ein Ausdruck ist zehn Shader-Uniforms. Die Messwerte drucken sie, und das engste Paar sagt, wie unterscheidbar der Satz ist — ein allein beurteiltes Gesicht wird gegen eine Erinnerung beurteilt.",
        "aspect.heads.for": "Das Gesicht wird im Shader gezeichnet, also können die billigen Stufen es ausdünnen statt löschen. Die Kopfhöhe in Pixeln ist die Zahl, an der ein Stufenwechsel beurteilt wird.",
        "aspect.speech.for": "Die Hüllkurven-Stufe kann oo nicht von ee unterscheiden; die spektrale kann es; die ausgerichtete braucht ein Transkript, das für diese zwei Aufnahmen niemand geschrieben hat — und sagt das.",
        "aspect.conversation.for": "Die Hälfte eines Gesprächs, die niemand animierte. Zuhören ausschalten, und derselbe Körper steht nur da, während jemand ihn anspricht.",
        "aspect.crowd.for": "Renderkosten sind eine Zahl von Quadern: Zeichenaufrufe, nicht Eckpunkte. Jede Figur ist zweiundzwanzig Quader bei Niedrig und vierundvierzig mit Fingern, auf jeder Maschine.",

        "shot.front": "vorn",
        "shot.quarter": "Dreiviertel",
        "shot.side": "Seite",
        "shot.back": "hinten",
        "shot.top": "oben",
        "shot.face": "Gesicht",
        "shot.profile": "Profil",
        "shot.work": "Arbeitsabstand",
        "shot.far": "fern",
        "shot.hand": "Hand",
        "shot.palm": "Handfläche",
        "shot.arm": "Arm",
        "shot.hands": "die Hände",
        "shot.close": "nah",
        "shot.over": "über die Schulter",

        "key.readout": "die Aspektkarte",
        "key.plot": "das Diagramm",
        "key.silhouette": "Silhouette",
        "key.shot": "nächste Einstellung",

        "plot.empty": "in dieser Szene nichts zu zeichnen",
        "banner.posing": "die Figuren werden gestellt…",

        "hint.idle": "1-9 wählt einen Aspekt · T startet die Tour · Rechtsziehen dreht · Rad zoomt",
        "hint.lineup": "Gehen oder Laufen auf der Karte · N dreht die Reihe · Uhr anhalten, um ein Bild zu vergleichen",
        "hint.gait": "Vorlage und Gefühl auf der Karte · N wechselt Seite, vorn, hinten, oben · Bilder rechts",
        "hint.gestures": "S reduziert auf die Silhouette · N dreht den Bogen · eine Spalte wählen vergrößert sie",
        "hint.action": "Boxen oder Arbeiten auf der Karte · Uhr anhalten und schrittweise vorrücken, um ein Bild einzufrieren",
        "hint.moves": "eine Technik wählen zeigt sie als Phasenstreifen · N dreht den Bogen",
        "hint.hands": "Haltungen und Arm auf der Karte · N geht die Nahaufnahmen durch · S für den Umriss",
        "hint.faces": "einen Ausdruck wählen füllt das Bild · N für das Profil",
        "hint.heads": "Gemessenes und Tätigkeit wählen · N geht die Entfernungen durch",
        "hint.speech": "eine Aufnahme auf der Karte abspielen · die drei Münder lesen dieselbe Datei",
        "hint.conversation": "einen Satz auf der Karte sagen · L schaltet das Zuhören · Sprecher tauschen",
        "hint.crowd": "Figuren und Detail rechts · andere GPU-Arbeit schließen, bevor eine Millisekunde gilt",

        "flow.character-tour.title": "wie eine Figur zusammengesetzt ist",
        "flow.character-tour.lineup": "Sechs Körper aus dem Reglerraum der parametrischen Figur, alle gehen einen Zyklus. Nichts wurde je Körper animiert: das Gangmodell leitet Tempo und Schrittlänge jeder Figur aus ihrem Körperbau ab.",
        "flow.character-tour.gait": "Ein Gang wird auf einem Bogen beurteilt. Das ist die Vorlage „betagt“, in acht Phasen eingefroren: t = 0 und 0,5 sind die Kontakte, 0,25 und 0,75 die Durchgänge. Ihr Zyklus dauert 1,11 s.",
        "flow.character-tour.gaitTop": "Von oben sind Schwanken und Wiegen das Einzige, was man sieht — deshalb wird ein Bogen aus vier Winkeln gelesen, bevor ein Gang fertig heißt.",
        "flow.character-tour.try": "Jetzt du: stell den Zyklus auf Laufen und sieh dem Bogen beim Neustellen zu. Die Zykluslänge in der Aufzeichnung ändert sich mit.",
        "flow.character-tour.try.hint": "die Zyklus-Chips stehen auf der Aspektkarte oben links",
        "flow.character-tour.run": "Dieselbe Vorlage über der Lauf-Basis: 0,63 s je Zyklus. Ein Gang ist eine Basis mal einen Faktorvektor, und beides sind Zahlen, die eine Aufzeichnung enthält.",
        "flow.character-tour.gestures": "Nun die Arme. Dreizehn Spalten, nichts bewegt sich: drei Handformen, drei gezielte Gesten durch den echten Löser und fünf eingefrorene Phasen der zwei Tätigkeitszyklen. Beurteilt wird der Satz.",
        "flow.character-tour.silhouette": "S drücken, oder warten: eine Tinte, kein Licht. Kann ein Fremder jede Spalte noch benennen? Eine Geste, die Schattierung zum Lesen braucht, überlebt keine Totale.",
        "flow.character-tour.action": "Der Boxzyklus, laufend von der Uhr des Labors — 1,70 s je Runde bei halber Intensität. Uhr anhalten und schrittweise vorrücken: ein Schlag, der schwebt, und einer, der sitzt, frieren zum selben Bild ein, also wird Bewegung hier beurteilt.",
        "flow.character-tour.moves": "Was eine Figur kann, nicht was sie ist: ein Kampfkunstsatz mit vierzehn Techniken, bei Bedarf geladen. Der tiefste Fuß bleibt am Boden — eine Zahl, kein Eindruck.",
        "flow.character-tour.hands": "Näher. Die gegliederte Hand neben dem einfachen Quader, gleiche Haltung, gleiches Licht. Ihre Handfläche ist bei diesem Körperbau 1,10 Armbreiten breit, und die Messwerte sagen, auf wie viele Pixel sie fällt.",
        "flow.character-tour.faces": "Die sechs Ausdrücke auf einem Kopf. Jeder ist zehn Shader-Uniforms; das engste Paar der sechs liegt in diesem Raum 1,206 auseinander — das macht „unterscheidbar“ zu einer Zahl.",
        "flow.character-tour.heads": "Drei Detailstufen desselben Kopfes im Arbeitsabstand, sprechend. Das Gesicht ist ein Shader, also dünnen die billigen Stufen es aus statt es zu löschen — die Kopfhöhe in Pixeln ist die Zahl, an der ein Wechsel beurteilt wird.",
        "flow.character-tour.speech": "Die Stimme: eine Aufnahme, drei Lippensynchron-Stufen. Die Hüllkurve kann oo nicht von ee unterscheiden, die spektrale kann es, und die ausgerichtete will ein Transkript, das niemand geschrieben hat.",
        "flow.character-tour.conversation": "Die Hälfte eines Gesprächs, die niemand animierte: ein Zuhörer. Zuhören auf der Karte ausschalten, und derselbe Körper steht nur da, während jemand ihn anspricht.",
        "flow.character-tour.crowd": "Was das alles kostet. Zwanzig Figuren bei Niedrig sind 440 Quader, und ein Quader ist ein Zeichenaufruf; Eckpunkte zählen kaum. Jede Zahl hier gehört dieser Maschine — die Form des Ergebnisses ist, was trägt.",
        "flow.character-tour.handoff": "Das ist die ganze Figur: ein Körper, ein Gang, die Arme, das Gesicht, eine Stimme, eine Menge — ein prozedurales Modell, und jeder Aspekt ein Szenario, das du messen kannst. Wähl eins und lies seine Karte."
    }
}
