// (c) Clayground Contributors - MIT License, see "LICENSE" file
.pragma library

// This lab's UI copy. Part names live in the kit's strings.js; everything the
// lab itself says is here. Key letters are physical and never translated: `W`
// stays `W` on a German keyboard.
var dict = {
    "en": {
        "lab.title": "ELECTRONICS 101",
        "lab.empty": "drag parts onto the board",

        "scenario.led-basic": "LED basics",
        "scenario.series": "series circuit",
        "scenario.parallel": "parallel circuit",
        "scenario.metering": "metering",
        "scenario.transistor": "transistor",
        "scenario.diode-or": "diode OR",
        "scenario.logic-and": "AND gate",
        "scenario.logic-or": "OR gate",
        "scenario.logic-xor": "XOR gate",
        "scenario.gates": "logic gate",
        "scenario.half-adder": "half adder",

        // what each preset is worth noticing - the micro-lesson that used to
        // live only in paper.md, now next to the preset that demonstrates it
        "scenario.note.led-basic": "one loop: the resistor sets the current, and the LED only lights one way round",
        "scenario.note.series": "one current everywhere \u2014 the volts divide between the two bulbs",
        "scenario.note.parallel": "one voltage across both \u2014 the current splits at the junction",
        "scenario.note.metering": "the ammeter sits IN the loop, the voltmeter ACROSS the part",
        "scenario.note.transistor": "0.8 mA into the base commands the 9.8 mA through the lamp — and the part would pass a hundred times its base current if the lamp asked",
        "scenario.note.diode-or": "either input lights the lamp — and the diodes are what keep the two inputs from driving each other",
        "scenario.note.logic-and": "two transistors in SERIES: the current must get past both, so both inputs have to be on",
        "scenario.note.logic-or": "the same two in PARALLEL: either path on its own is enough",
        "scenario.note.logic-xor": "exactly one — (A or B) and not (A and B), and that costs five transistors",
        "scenario.note.gates": "one chip, six functions: select it and switch what it does — the package, the symbol and the table all follow. Unwire VCC and it stops answering",
        "scenario.note.half-adder": "two gates reading the same two inputs: SUM is A xor B, CARRY is A and B — which is binary addition, and the first thing gates were ever built for",

        // key map (LabHelp renders these next to the keys that trigger them)
        "key.clear": "clear the board",
        "key.eraser": "eraser",
        "key.values": "show every value",
        "key.plan": "schematic",
        "key.planmax": "schematic, full window",
        "key.watch": "plot the selected part",
        "key.rotate": "turn the part",
        "key.grid": "grid mode",
        "key.delete": "remove the selection",

        "btn.eraser": "Eraser  (E)",
        "btn.eraser.on": "ERASER ON  (E)",
        "btn.values.on": "Values: on  (V)",
        "btn.values.off": "Values: off  (V)",
        "btn.grid.snap": "Grid: snap  (#)",
        "btn.grid.free": "Grid: free  (#)",
        "btn.clear": "Clear board  (C)",
        "btn.view": "View %1°   reset (0)",

        "plan.title": "SCHEMATIC",
        "plan.open": "open it (Z)",
        "plan.close": "back to the corner (Z or Esc)",

        "section.presets": "PRESETS",
        "section.parts": "PARTS",
        "section.tools": "TOOLS",

        "truth.title": "TRUTH TABLE",
        "truth.out": "OUT",
        "truth.sum": "SUM",
        "truth.carry": "CARRY",
        "truth.note": "measured, not printed — every row is this board solved again",

        "card.watch": "plot it (Q)",
        "card.watched": "on the plot ✓",
        "card.watch.full": "plot is full",
        "card.hint.resistor": "drag to set Ω · R turn · Del remove",
        "card.hint.battery": "drag to set volts · R turn · Del remove",
        "card.hint.part": "R turn · Del remove · drag to move",

        "cell.reaches": "reaches your parts",
        "cell.lost": "lost inside the cell",
        "cell.short": "short: your circuit is only %1 Ω, less than the cell itself",
        "cell.heavy": "heavy: %1 A drawn, rated %2 A",
        "cell.ok": "your circuit is %1",
        "cell.open": "open",

        "banner.short": "⚠ SHORT CIRCUIT — the current skips your parts and the cell heats up",
        "banner.heavy": "⚠ heavy load — more current than the cell is rated for",

        "quantity.current": "current",
        "quantity.voltage": "voltage",
        "quantity.power": "power",
        "hint.placing": "the ghost shows where it lands · click places it · Esc or right-click puts it down",
        "plot.empty": "select a part · Q puts it here",

        "hint.eraser": "eraser: click parts or wire knots to remove · E exits",
        "hint.actuator": "click the switch to flip it · the pads wire",
        "hint.actuator.pick": "click to pick this switch · then flip it here or on the card",
        "hint.wiring": "click a second pad — or any wire, to tap into it · right-click or Esc cancels",
        "hint.selected": "R turns the part · Q plots it · Del removes it · drag moves it",
        "hint.selected.free": " (Alt snaps)",
        "hint.selected.snap": " (Alt places freely)",
        "hint.selected.frame": " · F frames it",
        "hint.idle": "click two gold pads to wire · click a wire to branch off it · select a resistor for its Ω · V shows values · right-drag turns the view",

        // --- flow: led-basics (SPIKE) ---
        "flow.led-basics.title": "Why does the LED light?",
        "flow.paused": "paused — you took over",
        "flow.next": "next ›",
        "flow.back": "‹ back",
        "flow.resume": "resume",
        "flow.leave": "✕ leave",
        "flow.showme": "show me",
        "flow.watching": "watching…",
        "flow.led-basics.empty": "Let's build the simplest circuit that lights an LED. Watch — I'll place the parts on the board.",
        "flow.led-basics.battery": "This is the cell. It pushes: 4.5 volts between its two pads, the gold one is plus.",
        "flow.led-basics.led": "The LED. It only conducts one way — and only above about 2 volts, its forward voltage.",
        "flow.led-basics.resistor": "And a 470 Ω resistor. Without it the LED would take all the current it can get and die. This is its seatbelt.",
        "flow.led-basics.wire": "Now the loop: cell to switch, switch to LED, LED through the resistor and back to the cell. Current needs a closed ring.",
        "flow.led-basics.flip": "Your turn: click the switch to close the circuit.",
        "flow.led-basics.flip.hint": "The switch is the small part with the tilted lever — one click flips it.",
        "flow.led-basics.lit": "There it is. 5.1 milliamps flow, and the LED glows.",
        "flow.led-basics.why": "Why 5.1 mA? The cell offers 4.5 V, the LED eats about 2.1 of them, and the rest — 2.4 V — falls across the resistor. 2.4 V over 470 Ω is 5.1 mA. The resistor sets the current.",
        "flow.led-basics.values": "Read it off the board: each part shows its own voltage and current. Same current everywhere in one ring — that is a series circuit.",
        "flow.led-basics.try": "Try it yourself: select the resistor and drag its slider. Less resistance, more current, brighter LED — until it gives up.",

        // --- flow: logic-gates ---
        "flow.logic-gates.title": "From one transistor to XOR",
        "flow.logic-gates.meet": "This is a transistor. Three legs: collector on the left, emitter on the right, base facing you — the board says which is which. A small current into the base lets a much larger one through the other two.",
        "flow.logic-gates.switch": "Your turn: close the switch, so a current can reach the base.",
        "flow.logic-gates.switch.hint": "The switch is the part with the tilted lever, in the middle column.",
        "flow.logic-gates.gain": "Read the two numbers. The meter in the base lead shows 0.80 mA; the lamp draws 9.8 — twelve times as much, and only because twelve times is all the lamp asks for. This transistor would pass a hundred times its base current. The ring at its foot is green: it is fully switched on, and the lamp, not the transistor, is what limits the current now.",
        "flow.logic-gates.and": "Now a gate. Two transistors in series — the series circuit again, with the switches made of silicon. The current has to get past both of them.",
        "flow.logic-gates.andtask": "Switch both inputs on.",
        "flow.logic-gates.andtask.hint": "One click per switch. The table on the right shows which row you are standing on.",
        "flow.logic-gates.or": "Put the same two in parallel and either one is a way through. That is OR — the parallel circuit, doing logic.",
        "flow.logic-gates.xor": "XOR is the awkward one: exactly one, never both. No such part exists. It is (A or B) AND NOT (A and B) — so the board now holds the OR pair you just built, a NAND made of two more in series, and a fifth transistor that the NAND cuts off when both inputs go high.",
        "flow.logic-gates.xortask": "Turn exactly one input on.",
        "flow.logic-gates.xortask.hint": "Either switch on its own will do.",
        "flow.logic-gates.both": "Now the other one as well. The NAND node collapses to almost nothing, the fifth transistor is cut off, and the lamp goes out — with more current available than ever.",
        "flow.logic-gates.cost": "Five transistors, eight resistors and a lamp, for one bit of a decision. A phone holds billions of them. That is what this part bought.",
        "flow.logic-gates.chip": "So nobody builds it twice. Everything on that last board is sold as one package: five pins, and the two on the short sides are the supply — a chip needs feeding like anything else. This one is doing exactly the XOR you just wired by hand.",
        "flow.logic-gates.chiptask": "Check it: turn exactly one input on.",
        "flow.logic-gates.chiptask.hint": "Either switch on its own. The table on the right is still four solves of the board, not a printed answer.",
        "flow.logic-gates.switchit": "And the package is not committed. Select it and pick another function — this one is now a NAND, and the table was re-measured, not re-typed. Six gates, one part, and no rewiring.",
        "flow.logic-gates.adder": "Two of them reading the same two inputs, and you have arithmetic: SUM is A xor B, CARRY is A and B. Both switches on, and it reads sum 0, carry 1 — which is how binary writes 1 + 1 = 10."
    },
    "de": {
        "lab.title": "ELEKTRONIK 101",
        "lab.empty": "Bauteile auf das Brett ziehen",

        "scenario.led-basic": "LED-Grundschaltung",
        "scenario.series": "Reihenschaltung",
        "scenario.parallel": "Parallelschaltung",
        "scenario.metering": "Messen",
        "scenario.transistor": "Transistor",
        "scenario.diode-or": "Dioden-ODER",
        "scenario.logic-and": "UND-Gatter",
        "scenario.logic-or": "ODER-Gatter",
        "scenario.logic-xor": "XOR-Gatter",
        "scenario.gates": "Logikgatter",
        "scenario.half-adder": "Halbaddierer",

        "scenario.note.led-basic": "ein Stromkreis: der Widerstand bestimmt den Strom, die LED leuchtet nur in einer Richtung",
        "scenario.note.series": "\u00fcberall derselbe Strom \u2014 die Spannung teilt sich auf die Lampen auf",
        "scenario.note.parallel": "dieselbe Spannung an beiden \u2014 der Strom teilt sich am Knoten",
        "scenario.note.metering": "das Amperemeter liegt IM Stromkreis, das Voltmeter parallel zum Bauteil",
        "scenario.note.transistor": "0,8 mA in die Basis steuern die 9,8 mA durch die Lampe — und das Bauteil ließe das Hundertfache seines Basisstroms durch, wenn die Lampe es verlangte",
        "scenario.note.diode-or": "jeder Eingang für sich bringt die Lampe zum Leuchten — und die Dioden sind es, die verhindern, dass ein Eingang den anderen mitzieht",
        "scenario.note.logic-and": "zwei Transistoren in REIHE: der Strom muss an beiden vorbei, also müssen beide Eingänge an sein",
        "scenario.note.logic-or": "dieselben zwei PARALLEL: jeder Weg für sich genügt",
        "scenario.note.logic-xor": "genau einer — (A oder B) und nicht (A und B), und das kostet fünf Transistoren",
        "scenario.note.gates": "ein Baustein, sechs Funktionen: auswählen und umschalten — Gehäuse, Symbol und Tabelle folgen. VCC abklemmen und er antwortet nicht mehr",
        "scenario.note.half-adder": "zwei Gatter an denselben beiden Eingängen: SUMME ist A xor B, ÜBERTRAG ist A und B — das ist binäres Addieren, und der erste Zweck von Gattern überhaupt",

        "key.clear": "Board leeren",
        "key.eraser": "Radierer",
        "key.values": "alle Werte zeigen",
        "key.plan": "Schaltplan",
        "key.planmax": "Schaltplan, ganzes Fenster",
        "key.watch": "Auswahl plotten",
        "key.rotate": "Bauteil drehen",
        "key.grid": "Raster",
        "key.delete": "Auswahl entfernen",

        "btn.eraser": "Radierer  (E)",
        "btn.eraser.on": "RADIERER AN  (E)",
        "btn.values.on": "Werte: an  (V)",
        "btn.values.off": "Werte: aus  (V)",
        "btn.grid.snap": "Raster: fest  (#)",
        "btn.grid.free": "Raster: frei  (#)",
        "btn.clear": "Brett leeren  (C)",
        "btn.view": "Blick %1°   zurück (0)",

        "plan.title": "SCHALTPLAN",
        "plan.open": "groß zeigen (Z)",
        "plan.close": "zurück in die Ecke (Z oder Esc)",

        "section.presets": "VORLAGEN",
        "section.parts": "BAUTEILE",
        "section.tools": "WERKZEUGE",

        "truth.title": "WAHRHEITSTABELLE",
        // "AUS" would read as "off" in a column of ones and zeros
        "truth.out": "AUSG",
        "truth.sum": "SUMME",
        "truth.carry": "ÜBERTRAG",
        "truth.note": "gemessen, nicht abgedruckt — jede Zeile ist diese Schaltung, noch einmal gerechnet",

        "card.watch": "aufs Diagramm (Q)",
        "card.watched": "im Diagramm ✓",
        "card.watch.full": "Diagramm ist voll",
        "card.hint.resistor": "ziehen für Ω · R drehen · Entf löschen",
        "card.hint.battery": "ziehen für Volt · R drehen · Entf löschen",
        "card.hint.part": "R drehen · Entf löschen · ziehen verschiebt",

        "cell.reaches": "kommt bei den Bauteilen an",
        "cell.lost": "in der Zelle verloren",
        "cell.short": "Kurzschluss: deine Schaltung hat nur %1 Ω, weniger als die Zelle selbst",
        "cell.heavy": "hohe Last: %1 A entnommen, zulässig %2 A",
        "cell.ok": "deine Schaltung hat %1",
        "cell.open": "kein geschlossener Kreis",

        "banner.short": "⚠ KURZSCHLUSS — der Strom umgeht deine Bauteile und die Zelle wird heiß",
        "banner.heavy": "⚠ hohe Last — mehr Strom, als die Zelle verträgt",

        "quantity.current": "Strom",
        "quantity.voltage": "Spannung",
        "quantity.power": "Leistung",
        "hint.placing": "der Schatten zeigt, wohin es kommt · Klick setzt es · Esc oder rechte Taste legt es weg",
        "plot.empty": "Bauteil wählen · Q stellt es hier dar",

        "hint.eraser": "Radierer: Bauteile oder Knoten anklicken zum Löschen · E beendet",
        "hint.actuator": "Schalter anklicken zum Umlegen · Kontakte verdrahten",
        "hint.actuator.pick": "anklicken zum Auswählen · dann hier oder auf der Karte schalten",
        "hint.wiring": "zweites Kontaktfeld anklicken — oder einen Draht, um dort abzuzweigen · rechte Taste oder Esc bricht ab",
        "hint.selected": "R dreht das Bauteil · Q stellt es dar · Entf löscht es · ziehen verschiebt",
        "hint.selected.free": " (Alt rastet ein)",
        "hint.selected.snap": " (Alt setzt frei)",
        "hint.selected.frame": " · F rückt es ins Bild",
        "hint.idle": "zwei goldene Kontaktfelder verbinden · Draht anklicken zweigt ab · V zeigt alle Werte · rechte Taste dreht die Ansicht",

        // --- flow: led-basics (SPIKE) ---
        "flow.led-basics.title": "Warum leuchtet die LED?",
        "flow.paused": "angehalten — du hast übernommen",
        "flow.next": "weiter ›",
        "flow.back": "‹ zurück",
        "flow.resume": "fortsetzen",
        "flow.leave": "✕ beenden",
        "flow.showme": "zeig es mir",
        "flow.watching": "beobachten…",
        "flow.led-basics.empty": "Wir bauen die einfachste Schaltung, die eine LED zum Leuchten bringt. Schau zu — ich lege die Bauteile aufs Brett.",
        "flow.led-basics.battery": "Das ist die Zelle. Sie drückt: 4,5 Volt zwischen ihren beiden Kontakten, der goldene ist Plus.",
        "flow.led-basics.led": "Die LED. Sie leitet nur in eine Richtung — und erst ab etwa 2 Volt, ihrer Durchlassspannung.",
        "flow.led-basics.resistor": "Und ein 470-Ω-Widerstand. Ohne ihn würde die LED jeden Strom nehmen, den sie bekommt, und durchbrennen. Er ist ihr Sicherheitsgurt.",
        "flow.led-basics.wire": "Jetzt der Kreis: Zelle zum Schalter, Schalter zur LED, LED über den Widerstand zurück zur Zelle. Strom braucht einen geschlossenen Ring.",
        "flow.led-basics.flip": "Du bist dran: klicke den Schalter, um den Kreis zu schließen.",
        "flow.led-basics.flip.hint": "Der Schalter ist das kleine Bauteil mit dem schrägen Hebel — ein Klick genügt.",
        "flow.led-basics.lit": "Da ist es. 5,1 Milliampere fließen, und die LED leuchtet.",
        "flow.led-basics.why": "Warum 5,1 mA? Die Zelle bietet 4,5 V, die LED nimmt davon etwa 2,1 — der Rest, 2,4 V, fällt über dem Widerstand ab. 2,4 V an 470 Ω sind 5,1 mA. Der Widerstand bestimmt den Strom.",
        "flow.led-basics.values": "Lies es am Brett ab: jedes Bauteil zeigt seine Spannung und seinen Strom. Überall derselbe Strom in einem Ring — das ist eine Reihenschaltung.",
        "flow.led-basics.try": "Probiere selbst: wähle den Widerstand und zieh seinen Schieber. Weniger Ohm, mehr Strom, hellere LED — bis sie aufgibt.",

        // --- flow: logic-gates ---
        "flow.logic-gates.title": "Von einem Transistor zum XOR",
        "flow.logic-gates.meet": "Das ist ein Transistor. Drei Beine: links der Kollektor, rechts der Emitter, die Basis zeigt zu dir — das Brett schreibt es dazu. Ein kleiner Strom in die Basis lässt einen viel größeren durch die beiden anderen.",
        "flow.logic-gates.switch": "Du bist dran: schließe den Schalter, damit ein Strom zur Basis kommt.",
        "flow.logic-gates.switch.hint": "Der Schalter ist das Bauteil mit dem schrägen Hebel, in der mittleren Spalte.",
        "flow.logic-gates.gain": "Lies die beiden Zahlen. Das Messgerät in der Basisleitung zeigt 0,80 mA; die Lampe zieht 9,8 — zwölfmal so viel, und nur deshalb zwölfmal, weil die Lampe nicht mehr verlangt. Dieser Transistor ließe das Hundertfache seines Basisstroms durch. Der Ring an seinem Fuß ist grün: er ist voll durchgesteuert, und jetzt begrenzt die Lampe den Strom, nicht mehr er.",
        "flow.logic-gates.and": "Jetzt ein Gatter. Zwei Transistoren in Reihe — wieder die Reihenschaltung, nur sind die Schalter jetzt aus Silizium. Der Strom muss an beiden vorbei.",
        "flow.logic-gates.andtask": "Schalte beide Eingänge ein.",
        "flow.logic-gates.andtask.hint": "Ein Klick pro Schalter. Die Tabelle rechts zeigt, in welcher Zeile du gerade stehst.",
        "flow.logic-gates.or": "Dieselben zwei parallel, und jeder für sich ist ein Weg hindurch. Das ist ODER — die Parallelschaltung, die Logik macht.",
        "flow.logic-gates.xor": "XOR ist das sperrige: genau einer, niemals beide. Ein solches Bauteil gibt es nicht. Es ist (A oder B) UND NICHT (A und B) — auf dem Brett liegen jetzt also das ODER-Paar von eben, ein NAND aus zwei weiteren in Reihe, und ein fünfter Transistor, den das NAND sperrt, sobald beide Eingänge oben sind.",
        "flow.logic-gates.xortask": "Schalte genau einen Eingang ein.",
        "flow.logic-gates.xortask.hint": "Jeder der beiden Schalter allein genügt.",
        "flow.logic-gates.both": "Und jetzt den zweiten dazu. Der NAND-Knoten bricht auf fast null zusammen, der fünfte Transistor sperrt, und die Lampe geht aus — bei mehr verfügbarem Strom als je zuvor.",
        "flow.logic-gates.cost": "Fünf Transistoren, acht Widerstände und eine Lampe, für ein einziges Bit einer Entscheidung. In einem Handy stecken Milliarden davon. Das ist es, was dieses Bauteil erkauft hat.",
        "flow.logic-gates.chip": "Deshalb baut das niemand zweimal. Alles vom letzten Brett gibt es als ein Gehäuse: fünf Anschlüsse, und die beiden an den Schmalseiten sind die Versorgung — ein Chip will gefüttert werden wie alles andere. Dieser hier macht genau das XOR, das du gerade von Hand verdrahtet hast.",
        "flow.logic-gates.chiptask": "Prüf es nach: schalte genau einen Eingang ein.",
        "flow.logic-gates.chiptask.hint": "Jeder Schalter allein genügt. Die Tabelle rechts sind immer noch vier Rechnungen der Schaltung, keine abgedruckte Antwort.",
        "flow.logic-gates.switchit": "Und das Gehäuse ist nicht festgelegt. Wähl es aus und nimm eine andere Funktion — jetzt ist es ein NAND, und die Tabelle wurde neu gemessen, nicht neu getippt. Sechs Gatter, ein Bauteil, kein Umverdrahten.",
        "flow.logic-gates.adder": "Zwei davon an denselben beiden Eingängen, und du hast Arithmetik: SUMME ist A xor B, ÜBERTRAG ist A und B. Beide Schalter an, und es steht Summe 0, Übertrag 1 — so schreibt das Binärsystem 1 + 1 = 10."
    }
}
