#!/bin/sh
# (c) Clayground Contributors - MIT License, see "LICENSE" file
#
# The spelling the skill, the READMEs and lab-check use. Keeping the entry
# point free of the .py suffix means a failing check names a command you can
# paste.
exec python3 "$(dirname "$0")/lab_table.py" "$@"
