#!/usr/bin/env python3
# (c) Clayground Contributors - MIT License, see "LICENSE" file
"""lab-sweep - run a lab study's matrix and tabulate what came back (#203).

    tools/lab-sweep/lab-sweep labs/street-network-101/studies/topology-four-houses
    tools/lab-sweep/lab-sweep <study> --check
    tools/lab-sweep/lab-sweep <study> --only topology=cross --seed 42

WHAT THIS IS, AND WHAT IT DELIBERATELY IS NOT
---------------------------------------------
It reads a study manifest, expands the run matrix, drives `clayrender` once
per cell, writes one run record per cell, and aggregates the objective across
seeds into a results table.

It contains NO optimization and no search. It does not decide what to sweep
next, does not stop early on a promising cell, does not fit anything. That is
not an omission - a runner that chose its own next experiment would be making
the scientific decisions, and those belong to whoever is asking the question.
The runner's whole job is to make "run exactly this, reproducibly" cheap.

Three properties it does owe:

*Deterministic.* Every run stops the frame ticker and advances the clock by
hand, because a frame is a wall-clock interval and a lab left to play itself
samples different instants on every machine. Steps in, sim seconds out. Two
sweeps of one manifest produce byte-identical records.

*Parallel-safe.* Runs share nothing: each gets its own isolated preferences
store, its own throwaway PNG and its own record path. `--jobs` is therefore
free of ordering effects, and the results table is assembled from the records
afterwards rather than from whatever order the jobs finished in.

*Budgeted.* `run.budget` in the manifest is a hard cap on matrix size, checked
before anything is launched.
"""

import argparse
import concurrent.futures
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import manifest as M           # noqa: E402
import record as R             # noqa: E402

TOOL = "tools/lab-sweep/lab-sweep"


def die(msg):
    print(f"lab-sweep: {msg}", file=sys.stderr)
    sys.exit(1)


def repo_root(start):
    """Walk up to the checkout root - records and commands are written
    repo-relative so they read the same on every machine."""
    d = os.path.abspath(start)
    while True:
        if os.path.isdir(os.path.join(d, ".git")) or os.path.isfile(os.path.join(d, ".git")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            return os.path.abspath(start)
        d = parent


def find_study(arg):
    """A study is a directory; naming its study.md is allowed and means the
    same thing."""
    p = os.path.abspath(arg)
    if os.path.isdir(p):
        doc = os.path.join(p, "study.md")
        if not os.path.isfile(doc):
            die(f"{arg} has no study.md")
        return p, doc
    if os.path.isfile(p):
        return os.path.dirname(p), p
    die(f"no such study: {arg}")


# --- the generated setup script --------------------------------------------

def js_lines(v):
    if v is None:
        return []
    return [v] if isinstance(v, str) else list(v)


def build_script(m, run, record_path, command, root):
    """The JS clayrender runs for one cell.

    The ORDER here is the determinism contract, and every line of it was
    earned:

      seed -> plan -> reset -> parameters -> warm-up -> record

    The plan is built before the reset because `clock.reset()` is what clears
    the probe series and the sim state; building afterwards would leave the
    warm-up measuring a world that changed under it. The parameters are set
    after the reset because a reset does not touch them and a run has to start
    from the study's values, not the lab's defaults. And the warm-up runs
    before recording starts because a fleet that is still filling is a
    transient: recording it would put the same ramp into every cell and hide
    the difference the study is asking about.
    """
    hz = m["run"]["stepHz"]
    step = f"1 / {hz}"
    L = ["// generated by " + TOOL + " - do not edit, edit the study manifest",
         "clock._frameTicker.running = false",
         f"clock.seed = {run.seed}"]
    L += js_lines(m.get("setup"))
    for name, lv in run.levels.items():
        kind = next(p["kind"] for p in m["parameters"] if p["name"] == name)
        if kind == "eval":
            L += js_lines(lv["eval"])
        elif kind == "scenario":
            L.append(f'applyScenario({json.dumps(lv["scenario"])})')
        elif kind == "param":
            L.append(f'Lab.set({json.dumps(name)}, {lv["value"]})')
    # The record's "scenario" field should say what this was a run OF. Without
    # this it inherits whatever the lab loaded with, and every record in the
    # sweep claims to be the same scenario.
    L.append(f"Lab.scenario = {json.dumps(run.cell)}")
    L.append("clock.reset()")
    for name, value in (m.get("fixed") or {}).items():
        L.append(f"Lab.set({json.dumps(name)}, {value})")

    warm = m["run"].get("warmupSteps", 0)
    if warm:
        L.append(f"for (var w = 0; w < {warm}; ++w) clock._advance({step})")

    steps = m["run"]["steps"]
    L += [
        f"recorder.lab = {json.dumps(m['lab'])}",
        f"recorder.destination = {json.dumps(os.path.relpath(record_path, root))}",
        f"recorder.recordId = {json.dumps(run.id)}",
        f"recorder.command = {json.dumps(command)}",
        f"recorder.probes = {json.dumps(M.recorded_probes(m))}",
        f"recorder.steps = {steps}",
        f"recorder.stepSize = {step}",
        "recorder.recording = true",
        f"for (var i = 0; i < {steps}; ++i) clock._advance({step})",
        "recorder.recording = false",
    ]
    return "\n".join(L) + "\n"


def regen_command(m, run):
    """What to put in the record's `command` field: the one invocation that
    reproduces THIS record and nothing else."""
    parts = [TOOL, m["studyPath"]]
    for name, lv in run.levels.items():
        parts.append(f"--only {name}={lv['id']}")
    parts.append(f"--seed {run.seed}")
    return " ".join(parts)


# --- driving clayrender ------------------------------------------------------

def sandbox_path(m, root):
    p = m["lab"]
    if not p.endswith(".qml"):
        p = os.path.join("labs", p, "Sandbox.qml")
    full = os.path.join(root, p)
    if not os.path.isfile(full):
        die(f'manifest "lab": {p} does not exist')
    return p


def run_clayrender(clayrender, sandbox, root, script_text, extra=None):
    """One render, fully isolated: its own prefs store, its own temp files.

    Returns (exit code, combined output).
    """
    tmp = tempfile.mkdtemp(prefix="lab-sweep-")
    try:
        script = os.path.join(tmp, "setup.js")
        with open(script, "w", encoding="utf-8") as f:
            f.write(script_text)
        cmd = [clayrender, sandbox,
               "--out", os.path.join(tmp, "frame.png"),
               "--size", "900x600", "--frames", "2",
               "--prefs", "isolated",
               "--script", script]
        cmd += extra or []
        p = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
        return p.returncode, (p.stdout or "") + (p.stderr or "")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def read_labinfo(clayrender, sandbox, root):
    """The lab's own labInfo(), for the mechanical answerability check.

    This loads the lab - there is no way to know what probes a QML file
    registers without letting it register them - but it advances no time and
    records nothing, which is what `--check` promises.
    """
    marker = "LAB-SWEEP-LABINFO "
    script = ("clock._frameTicker.running = false\n"
              'console.log("' + marker + '" + JSON.stringify('
              "Object.assign({ scenarios: (typeof scenarios === 'function') "
              "? scenarios() : null }, labInfo())))\n")
    code, out = run_clayrender(clayrender, sandbox, root, script)
    for line in out.splitlines():
        at = line.find(marker)
        if at != -1:
            try:
                return json.loads(line[at + len(marker):])
            except json.JSONDecodeError as e:
                die(f"the lab's labInfo() is not JSON: {e}")
    die("could not read labInfo() from the lab "
        f"(clayrender exit {code}).\n{out.strip()}")


def do_run(args, m, run, root, sandbox, records_dir):
    path = os.path.join(records_dir, run.id + ".labrec")
    text = build_script(m, run, path, regen_command(m, run), root)
    code, out = run_clayrender(args.clayrender, sandbox, root, text)
    ok = code == 0 and os.path.isfile(path)
    return run, ok, code, out, path


# --- the results table -------------------------------------------------------

def fmt(v, digits=3):
    if v is None:
        return "-"
    return f"{v:.{digits}f}"


def objective_of(m, rec):
    """One record's objective value.

    Normalizing divides the statistic by another statistic of the SAME probe,
    which is what makes a spread comparable between cells whose scales differ
    - see NORMALIZERS in manifest.py for the mistake that put it here.
    """
    obj = m["objective"]
    v = rec.stat(obj["probe"], obj["statistic"])
    norm = obj.get("normalize")
    if norm is None:
        return v
    d = rec.stat(obj["probe"], norm)
    if not d:
        raise R.RecordError(
            f"record {rec.id}: cannot normalize by {norm}({obj['probe']}), "
            "which is zero - the probe measured nothing in this run")
    return v / d


def objective_name(m):
    obj = m["objective"]
    base = f'{obj["statistic"]}({obj["probe"]})'
    norm = obj.get("normalize")
    return base if norm is None else f'{base} / {norm}({obj["probe"]})'


def aggregate(m, results):
    """Per cell: the objective averaged over seeds, and its spread across
    them. Seeds are averaged rather than pooled because each run is one noise
    realisation of the same configuration - and the spread ACROSS seeds is the
    number that says whether a difference between cells means anything."""
    obj = m["objective"]
    cells = {}
    for run, rec in results:
        cells.setdefault(run.cell, {"label": run.label(), "runs": []})
        cells[run.cell]["runs"].append((run, rec))

    rows = []
    for cell, data in cells.items():
        values = [objective_of(m, rec) for _, rec in data["runs"]]
        extra = []
        for spec in m.get("report", []):
            xs = [rec.stat(spec["probe"], spec["statistic"])
                  for _, rec in data["runs"]]
            extra.append(sum(xs) / len(xs))
        mean = sum(values) / len(values)
        spread = (max(values) - min(values)) if len(values) > 1 else 0.0
        rows.append({"cell": cell, "label": data["label"], "n": len(values),
                     "objective": mean, "spread": spread, "extra": extra,
                     "runs": data["runs"]})
    rows.sort(key=lambda r: r["objective"],
              reverse=obj["direction"] == "maximize")
    return rows


def results_table(m, rows, study_rel):
    obj = m["objective"]
    verb = "lowest" if obj["direction"] == "minimize" else "highest"
    stat = objective_name(m)
    report = m.get("report", [])
    cols = [f'{s["statistic"]}({s["probe"]})' for s in report]
    L = [
        "<!-- generated by " + TOOL + " - do not edit by hand;",
        "     re-run the sweep and this file is rewritten from the records. -->",
        f"# Results — {m['study']}",
        "",
        f"Objective: **{verb} {stat}**, averaged over "
        f"{len(m['seeds'])} seeds ({', '.join(str(s) for s in m['seeds'])}).",
        "Every number below is read out of a committed run record in "
        "`records/`; none of it is typed by hand.",
        "",
        f"```\n{TOOL} {study_rel}\n```",
        "",
        "## By configuration",
        "",
    ]
    head = ["rank", "configuration", f"{stat}", "seed spread"] + cols + ["runs"]
    L.append("| " + " | ".join(head) + " |")
    L.append("|" + "|".join(["---"] * len(head)) + "|")
    for i, r in enumerate(rows, 1):
        cells = [str(i), f"`{r['cell']}`", fmt(r["objective"]), fmt(r["spread"])]
        cells += [fmt(v) for v in r["extra"]]
        cells.append(str(r["n"]))
        L.append("| " + " | ".join(cells) + " |")

    head2 = ["record", "configuration", "seed", stat] + cols
    L += ["", "## Every run", "",
          "| " + " | ".join(head2) + " |",
          "|" + "|".join(["---"] * len(head2)) + "|"]
    for r in rows:
        for run, rec in sorted(r["runs"], key=lambda x: x[0].seed):
            vals = [fmt(objective_of(m, rec))]
            vals += [fmt(rec.stat(s["probe"], s["statistic"])) for s in report]
            L.append(f"| `{run.id}.labrec` | `{r['cell']}` | {run.seed} | "
                     + " | ".join(vals) + " |")
    L.append("")
    return "\n".join(L)


# --- main --------------------------------------------------------------------

def parse_only(values):
    out = {}
    for v in values or []:
        if "=" not in v:
            die(f"--only {v}: expected NAME=LEVEL")
        name, level = v.split("=", 1)
        out.setdefault(name, []).append(level)
    return out


def main():
    ap = argparse.ArgumentParser(
        prog="lab-sweep",
        description="Run a lab study's matrix and tabulate the objective.")
    ap.add_argument("study", help="the study directory (or its study.md)")
    ap.add_argument("--check", action="store_true",
                    help="validate the manifest, and everything it names "
                         "against the lab's labInfo(), then exit without "
                         "running the matrix")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the run matrix and exit")
    ap.add_argument("--only", action="append", metavar="NAME=LEVEL",
                    help="restrict a varied parameter (repeatable)")
    ap.add_argument("--seed", action="append", type=int,
                    help="restrict to these seeds (repeatable)")
    ap.add_argument("--jobs", type=int, default=4, help="parallel runs")
    ap.add_argument("--clayrender", default=None,
                    help="path to clayrender (default: build/bin/clayrender)")
    args = ap.parse_args()

    study_dir, doc = find_study(args.study)
    root = repo_root(study_dir)
    with open(doc, "r", encoding="utf-8") as f:
        text = f.read()
    try:
        m = M.parse(text)
    except M.ManifestError as e:
        die(str(e))
    m["studyPath"] = os.path.relpath(study_dir, root)

    if args.clayrender is None:
        args.clayrender = os.path.join(root, "build", "bin", "clayrender")
    sandbox = sandbox_path(m, root)

    try:
        runs = M.expand(m, parse_only(args.only), args.seed)
    except M.ManifestError as e:
        die(str(e))

    print(f"study   {m['study']}  ({m['studyPath']})")
    print(f"lab     {sandbox}")
    print(f"matrix  {M.matrix_size(m)} runs, budget {m['run']['budget']}"
          + (f"  ->  {len(runs)} selected" if len(runs) != M.matrix_size(m) else ""))
    print(f"each    {m['run'].get('warmupSteps', 0)} warm-up + "
          f"{m['run']['steps']} steps at 1/{m['run']['stepHz']} s")

    if args.dry_run:
        for r in runs:
            print(f"  {r.id}")
        return 0

    if not os.path.isfile(args.clayrender):
        die(f"clayrender not found at {args.clayrender} - build it first "
            "(cmake --build build --target clayrender)")

    if args.check:
        info = read_labinfo(args.clayrender, sandbox, root)
        errors = M.check_against_lab(m, info)
        if errors:
            print("\nanswerability check FAILED:")
            for e in errors:
                print(f"  - {e}")
            print("\nThis is the mechanical half only. A manifest that passes "
                  "it still has to argue, in the study, that the model holds "
                  "for the question - see the kit's model card.")
            return 1
        print("\nanswerability check passed (mechanically): every probe and "
              "parameter this study names exists in the lab.")
        print("The other half is not mechanical: the study must still argue "
              "from the model card that the model holds for the question.")
        return 0

    records_dir = os.path.join(study_dir, "records")
    os.makedirs(records_dir, exist_ok=True)

    print()
    failures, done = [], []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, args.jobs)) as ex:
        futures = [ex.submit(do_run, args, m, r, root, sandbox, records_dir)
                   for r in runs]
        for fut in concurrent.futures.as_completed(futures):
            run, ok, code, out, path = fut.result()
            if ok:
                size = os.path.getsize(path)
                print(f"  ok    {run.id}  ({size} bytes)")
                done.append((run, path))
            else:
                print(f"  FAIL  {run.id}  (clayrender exit {code})")
                failures.append((run, code, out))

    if failures:
        print()
        for run, code, out in failures:
            print(f"--- {run.id} (exit {code}) " + "-" * 20)
            print(out.strip()[-2000:])
        die(f"{len(failures)} of {len(runs)} runs failed; no table written")

    results = [(run, R.read(path)) for run, path in
               sorted(done, key=lambda x: x[0].id)]
    rows = aggregate(m, results)
    table = results_table(m, rows, m["studyPath"])
    out_path = os.path.join(study_dir, "results.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(table)

    print(f"\n{len(results)} records -> {os.path.relpath(out_path, root)}")
    best = rows[0]
    print(f"best: {best['label']}  "
          f"{objective_name(m)} = {fmt(best['objective'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
