// (c) Clayground Contributors - MIT License, see "LICENSE" file
.pragma library

// The explain bench's own vocabulary: the four approaches as scenarios, the
// transistor's parts by their anatomy.js ids, the callout details, the chalk
// labels and the narration of the four lessons - one lesson per approach,
// all teaching the same thing so the mechanisms can be compared and not the
// words. Registered by Sandbox.qml before the first applyScenario.
var dict = {
    "en": {
        "explain.title": "EXPLAIN BENCH",
        "explain.state": "STATE",

        "scenario.exploded": "exploded view",
        "scenario.callouts": "callouts",
        "scenario.chalkboard": "chalkboard",
        "scenario.inside": "dive in",
        "scenario.note.exploded": "the part comes apart in place — the professor points at each piece",
        "scenario.note.callouts": "rings and captions on the sub-parts, one after another; the case can be ghosted",
        "scenario.note.chalkboard": "a cut to a slate: the cross-section and the gain graph draw themselves",
        "scenario.note.inside": "the professor shrinks, the camera flies in, and the die is a landscape with carriers",

        // parts, by anatomy.js id
        "explain.part.part": "transistor",
        "explain.part.print": "silkscreen",
        "explain.part.leg.collector": "collector",
        "explain.part.leg.base": "base",
        "explain.part.leg.emitter": "emitter",
        "explain.part.case": "epoxy case",
        "explain.part.face": "flat face",
        "explain.part.header": "header",
        "explain.part.die.collector": "collector layer (N)",
        "explain.part.die.base": "base layer (P)",
        "explain.part.die.emitter": "emitter layer (N)",
        "explain.part.wires": "bond wires",
        // the interior, by TransistorInterior3D id
        "explain.part.collector": "collector (N)",
        "explain.part.base": "base (P)",
        "explain.part.emitter": "emitter (N)",
        "explain.part.junction.eb": "emitter–base junction",
        "explain.part.junction.bc": "base–collector junction",

        // one line under each callout card
        "explain.detail.leg.collector": "the leg the working current comes in by (by convention)",
        "explain.detail.leg.base": "a small current here controls the large one",
        "explain.detail.leg.emitter": "the leg it leaves by, joined by the base current",
        "explain.detail.case": "epoxy — protects a chip a tenth its size",
        "explain.detail.face": "the flat side is the base's side; that is how you orient it",
        "explain.detail.die.collector": "the wide bottom layer, bonded to the collector's tab",
        "explain.detail.die.base": "the thin middle layer — everything is decided here",
        "explain.detail.die.emitter": "the small top island the current enters through",
        "explain.detail.wires": "hair-thin gold, from the die up to the base and emitter legs",

        // chalk
        "explain.chalk.n": "N",
        "explain.chalk.p": "P",
        "explain.chalk.collector": "collector",
        "explain.chalk.base": "base",
        "explain.chalk.emitter": "emitter",
        "explain.chalk.ib": "I_B  0.8 mA",
        "explain.chalk.ic": "I_C  9.8 mA",
        "explain.chalk.ibAxis": "I_B",
        "explain.chalk.icAxis": "I_C",
        "explain.chalk.beta": "I_C ≈ 12 · I_B",

        // bench buttons and keys
        "explain.btn.explode": "take it apart",
        "explain.btn.assemble": "put it together",
        "explain.btn.xray": "x-ray the case",
        "explain.btn.solid": "solid case",
        "explain.btn.focus": "focus next part",
        "explain.btn.callout.next": "next callout",
        "explain.btn.callout.all": "all callouts",
        "explain.btn.callout.none": "no callouts",
        "explain.btn.chalk.open": "cut to the board",
        "explain.btn.chalk.close": "back to the bench",
        "explain.btn.chalk.draw": "draw it",
        "explain.btn.chalk.section": "the cross-section",
        "explain.btn.chalk.graph": "the gain graph",
        "explain.btn.dive.in": "go inside",
        "explain.btn.dive.out": "come back out",
        "explain.btn.currents": "base current",
        "explain.key.explode": "take apart / put together",
        "explain.key.xray": "x-ray the case on / off",
        "explain.key.focus": "focus the next part",
        "explain.key.callout.next": "reveal the next callout",
        "explain.key.callout.all": "reveal every callout",
        "explain.key.callout.none": "hide the callouts",
        "explain.key.chalk": "cut to the chalkboard / back",
        "explain.key.chalk.draw": "draw the board (rewind when drawn)",
        "explain.key.chalk.graph": "switch the drawing",
        "explain.key.dive": "dive in / come back out",
        "explain.key.currents": "cycle the base current",

        // --- lesson 1: the exploded view ---------------------------------
        "flow.explain-exploded.title": "Take the transistor apart",
        "flow.explain-exploded.meet": "This is a transistor: a black case, three legs. Everything it does happens inside, where you cannot see it.",
        "flow.explain-exploded.legs": "Collector, base, emitter — the board prints which is which. Two of them carry the working current; the base is the control.",
        "flow.explain-exploded.open": "Let us take it apart. The case lifts off — it only protects what is inside.",
        "flow.explain-exploded.die": "A chip of silicon, smaller than a grain of rice, sits on the collector's metal tab.",
        "flow.explain-exploded.layers": "Three layers: N, a thin P, and N again. The thin one in the middle is the base — what the transistor does is decided there.",
        "flow.explain-exploded.wires": "Two hair-thin gold wires connect the base and the emitter to their legs. The collector is the tab itself.",
        "flow.explain-exploded.close": "Back together. From outside, a black lump — but you now know what the three legs lead to.",

        // --- lesson 2: callouts ------------------------------------------
        "flow.explain-callouts.title": "Label the transistor",
        "flow.explain-callouts.meet": "The same transistor, and nothing gets taken apart this time. Let me label what you can see.",
        "flow.explain-callouts.legs": "Collector, base, emitter: the card by each leg says what it does.",
        "flow.explain-callouts.case": "The case is epoxy — a shell you cannot see through. So let me make it see-through.",
        "flow.explain-callouts.inside": "Inside: the die with its three layers, and the wires up to the legs. Each card names one.",
        "flow.explain-callouts.all": "Now you can name every part. What the base does to the current is the next lesson.",

        // --- lesson 3: the chalkboard ------------------------------------
        "flow.explain-chalkboard.title": "Draw the transistor",
        "flow.explain-chalkboard.meet": "This is a transistor. What happens inside is far too small to see — so let us draw it.",
        "flow.explain-chalkboard.layers": "Three layers of silicon: a wide N collector at the bottom, a thin P base, and a small N emitter on top.",
        "flow.explain-chalkboard.currents": "A small current into the base, I_B, opens the way — and a much larger one flows from collector to emitter, I_C.",
        "flow.explain-chalkboard.graph": "As a graph it is a line: I_C is about twelve times I_B, until the lamp cannot take more and the line goes flat.",
        "flow.explain-chalkboard.back": "Back to the bench. The drawing is what the black case hides: three layers and two currents.",

        // --- lesson 4: the dive ------------------------------------------
        "flow.explain-inside.title": "Go inside the transistor",
        "flow.explain-inside.meet": "This transistor is switched on: 0.8 milliamps into the base, 9.8 through the lamp. Let us go and see where that happens.",
        "flow.explain-inside.dive": "Down we go — through the case, onto the chip. The scale is a lie; the layout is not.",
        "flow.explain-inside.layers": "We stand on the emitter. Below us the thin base, and below that the wide collector. Three layers, two junctions.",
        "flow.explain-inside.flow": "Watch the carriers: electrons pour from the emitter through the base into the collector. The few the base draws off are the base current.",
        "flow.explain-inside.control": "Cut the base current and everything stops. That is the whole trick: the small current lets the big one pass.",
        "flow.explain-inside.surface": "Back out. From the bench nothing has changed — but you have seen what the base does."
    },
    "de": {
        "explain.title": "ERKLÄR-BANK",
        "explain.state": "ZUSTAND",

        "scenario.exploded": "Explosionsansicht",
        "scenario.callouts": "Beschriftungen",
        "scenario.chalkboard": "Tafel",
        "scenario.inside": "Hineintauchen",
        "scenario.note.exploded": "das Bauteil geht an Ort und Stelle auseinander — der Professor zeigt auf jedes Teil",
        "scenario.note.callouts": "Ringe und Kärtchen an den Teilen, eins nach dem anderen; das Gehäuse wird durchsichtig",
        "scenario.note.chalkboard": "Schnitt zur Tafel: Querschnitt und Verstärkungskurve zeichnen sich selbst",
        "scenario.note.inside": "der Professor schrumpft, die Kamera fliegt hinein, der Chip wird zur Landschaft mit Ladungsträgern",

        "explain.part.part": "Transistor",
        "explain.part.print": "Aufdruck",
        "explain.part.leg.collector": "Kollektor",
        "explain.part.leg.base": "Basis",
        "explain.part.leg.emitter": "Emitter",
        "explain.part.case": "Epoxidgehäuse",
        "explain.part.face": "flache Seite",
        "explain.part.header": "Träger",
        "explain.part.die.collector": "Kollektorschicht (N)",
        "explain.part.die.base": "Basisschicht (P)",
        "explain.part.die.emitter": "Emitterschicht (N)",
        "explain.part.wires": "Bonddrähte",
        "explain.part.collector": "Kollektor (N)",
        "explain.part.base": "Basis (P)",
        "explain.part.emitter": "Emitter (N)",
        "explain.part.junction.eb": "Emitter-Basis-Übergang",
        "explain.part.junction.bc": "Basis-Kollektor-Übergang",

        "explain.detail.leg.collector": "das Bein, durch das der Arbeitsstrom hereinkommt (technische Stromrichtung)",
        "explain.detail.leg.base": "ein kleiner Strom hier steuert den großen",
        "explain.detail.leg.emitter": "das Bein, durch das er hinausgeht, zusammen mit dem Basisstrom",
        "explain.detail.case": "Epoxid — schützt einen Chip von einem Zehntel seiner Größe",
        "explain.detail.face": "die flache Seite ist die Basisseite; daran richtet man es aus",
        "explain.detail.die.collector": "die breite untere Schicht, auf den Kollektorträger gebondet",
        "explain.detail.die.base": "die dünne Schicht in der Mitte — hier entscheidet sich alles",
        "explain.detail.die.emitter": "die kleine Insel oben, durch die der Strom eintritt",
        "explain.detail.wires": "haarfeines Gold, vom Chip hinauf zu Basis- und Emitterbein",

        "explain.chalk.n": "N",
        "explain.chalk.p": "P",
        "explain.chalk.collector": "Kollektor",
        "explain.chalk.base": "Basis",
        "explain.chalk.emitter": "Emitter",
        "explain.chalk.ib": "I_B  0,8 mA",
        "explain.chalk.ic": "I_C  9,8 mA",
        "explain.chalk.ibAxis": "I_B",
        "explain.chalk.icAxis": "I_C",
        "explain.chalk.beta": "I_C ≈ 12 · I_B",

        "explain.btn.explode": "auseinandernehmen",
        "explain.btn.assemble": "zusammensetzen",
        "explain.btn.xray": "Gehäuse durchleuchten",
        "explain.btn.solid": "Gehäuse massiv",
        "explain.btn.focus": "nächstes Teil hervorheben",
        "explain.btn.callout.next": "nächste Beschriftung",
        "explain.btn.callout.all": "alle Beschriftungen",
        "explain.btn.callout.none": "keine Beschriftungen",
        "explain.btn.chalk.open": "Schnitt zur Tafel",
        "explain.btn.chalk.close": "zurück zur Bank",
        "explain.btn.chalk.draw": "zeichnen",
        "explain.btn.chalk.section": "der Querschnitt",
        "explain.btn.chalk.graph": "die Verstärkungskurve",
        "explain.btn.dive.in": "hineingehen",
        "explain.btn.dive.out": "wieder heraus",
        "explain.btn.currents": "Basisstrom",
        "explain.key.explode": "auseinander / zusammen",
        "explain.key.xray": "Gehäuse durchleuchten an / aus",
        "explain.key.focus": "nächstes Teil hervorheben",
        "explain.key.callout.next": "nächste Beschriftung zeigen",
        "explain.key.callout.all": "alle Beschriftungen zeigen",
        "explain.key.callout.none": "Beschriftungen ausblenden",
        "explain.key.chalk": "Schnitt zur Tafel / zurück",
        "explain.key.chalk.draw": "Tafel zeichnen (zurückspulen, wenn fertig)",
        "explain.key.chalk.graph": "Zeichnung wechseln",
        "explain.key.dive": "hinein / wieder heraus",
        "explain.key.currents": "Basisstrom durchschalten",

        "flow.explain-exploded.title": "Den Transistor auseinandernehmen",
        "flow.explain-exploded.meet": "Das ist ein Transistor: ein schwarzes Gehäuse, drei Beine. Alles, was er tut, passiert innen, wo man es nicht sieht.",
        "flow.explain-exploded.legs": "Kollektor, Basis, Emitter — das Brett schreibt dazu, welches welches ist. Zwei führen den Arbeitsstrom; die Basis steuert.",
        "flow.explain-exploded.open": "Nehmen wir ihn auseinander. Das Gehäuse hebt sich ab — es schützt nur, was darin ist.",
        "flow.explain-exploded.die": "Ein Chip aus Silizium, kleiner als ein Reiskorn, sitzt auf dem Metallträger des Kollektors.",
        "flow.explain-exploded.layers": "Drei Schichten: N, ein dünnes P, wieder N. Die dünne in der Mitte ist die Basis — dort entscheidet sich, was der Transistor tut.",
        "flow.explain-exploded.wires": "Zwei haarfeine Golddrähte verbinden Basis und Emitter mit ihren Beinen. Der Kollektor ist der Träger selbst.",
        "flow.explain-exploded.close": "Wieder zusammen. Von außen ein schwarzer Klumpen — aber jetzt weißt du, wohin die drei Beine führen.",

        "flow.explain-callouts.title": "Den Transistor beschriften",
        "flow.explain-callouts.meet": "Derselbe Transistor, und diesmal wird nichts auseinandergenommen. Ich beschrifte, was du siehst.",
        "flow.explain-callouts.legs": "Kollektor, Basis, Emitter: das Kärtchen an jedem Bein sagt, was es tut.",
        "flow.explain-callouts.case": "Das Gehäuse ist Epoxid — eine Hülle, durch die man nicht sieht. Also mache ich sie durchsichtig.",
        "flow.explain-callouts.inside": "Innen: der Chip mit seinen drei Schichten, und die Drähte hinauf zu den Beinen. Jedes Kärtchen nennt eines.",
        "flow.explain-callouts.all": "Jetzt kannst du jedes Teil benennen. Was die Basis mit dem Strom macht, ist die nächste Lektion.",

        "flow.explain-chalkboard.title": "Den Transistor zeichnen",
        "flow.explain-chalkboard.meet": "Das ist ein Transistor. Was innen passiert, ist viel zu klein, um es zu sehen — also zeichnen wir es.",
        "flow.explain-chalkboard.layers": "Drei Schichten Silizium: unten ein breiter N-Kollektor, eine dünne P-Basis, oben ein kleiner N-Emitter.",
        "flow.explain-chalkboard.currents": "Ein kleiner Strom in die Basis, I_B, öffnet den Weg — und ein viel größerer fließt vom Kollektor zum Emitter, I_C.",
        "flow.explain-chalkboard.graph": "Als Kurve ist es eine Gerade: I_C ist etwa zwölfmal I_B, bis die Lampe nicht mehr verlangt und die Linie flach wird.",
        "flow.explain-chalkboard.back": "Zurück zur Bank. Die Zeichnung ist, was das schwarze Gehäuse verbirgt: drei Schichten und zwei Ströme.",

        "flow.explain-inside.title": "In den Transistor hinein",
        "flow.explain-inside.meet": "Dieser Transistor ist durchgeschaltet: 0,8 Milliampere in die Basis, 9,8 durch die Lampe. Gehen wir nachsehen, wo das passiert.",
        "flow.explain-inside.dive": "Hinunter — durch das Gehäuse, auf den Chip. Der Maßstab ist gelogen; der Aufbau nicht.",
        "flow.explain-inside.layers": "Wir stehen auf dem Emitter. Unter uns die dünne Basis, darunter der breite Kollektor. Drei Schichten, zwei Übergänge.",
        "flow.explain-inside.flow": "Sieh die Ladungsträger: Elektronen strömen vom Emitter durch die Basis in den Kollektor. Die wenigen, die die Basis abzweigt, sind der Basisstrom.",
        "flow.explain-inside.control": "Nimm den Basisstrom weg, und alles steht. Das ist der ganze Trick: der kleine Strom lässt den großen durch.",
        "flow.explain-inside.surface": "Wieder heraus. Von der Bank aus hat sich nichts verändert — aber du hast gesehen, was die Basis tut."
    }
}
