// (c) Clayground Contributors - MIT License, see "LICENSE" file
.pragma library

// The character kit's own vocabulary: what the aspects, the gestures, the
// moves, the expressions, the builds and the readings are called. A lab using
// this kit registers it with LabLang first and its own dictionary second, so
// the lab may override any key. Key letters are physical and never
// translated.
//
// The move names are the martial-arts set's own (MartialArts.qml); the
// preset names are gait.js's PRESETS. Both are data the plugin owns, so the
// keys here follow those spellings exactly.
var dict = {
    "en": {
        "param.frames": "frames on the sheet",
        "param.maturity": "maturity",
        "param.femininity": "femininity",
        "param.mass": "mass",
        "param.muscle": "muscle",
        "param.intensity": "intensity",
        "param.workHeight": "work height",
        "param.count": "characters",
        "param.roundness": "chamfer on every box",
        "param.scale": "figure scale",
        "param.handScale": "hand scale",
        "param.handBuild": "hand takes of the build",

        "choice.base": "cycle",
        "choice.preset": "preset",
        "choice.emotion": "emotion",
        "choice.gesture": "column",
        "choice.action": "action",
        "choice.move": "move",
        "choice.pose": "hand pose",
        "choice.arm": "arm",
        "choice.expression": "expression",
        "choice.subject": "subject",
        "choice.activity": "the face does",
        "choice.detail": "detail",
        "choice.walking": "the crowd",
        "choice.solo": "shown",
        "choice.recording": "recording",
        "choice.transport": "transport",
        "choice.speaker": "speaker",
        "choice.listening": "the other one",
        "choice.build": "build",
        "choice.gloves": "hands",
        "choice.props": "props",

        "base.walk": "walk",
        "base.run": "run",

        "preset.": "none",
        "preset.neutral": "neutral",
        "preset.cheerful": "cheerful",
        "preset.dejected": "dejected",
        "preset.furious": "furious",
        "preset.elderly": "elderly",
        "preset.toddler": "toddler",
        "preset.heavy": "heavy",
        "preset.sneak": "sneak",
        "preset.proud": "proud",
        "preset.march": "march",

        "emotion.": "none",
        "emotion.happy": "happy",
        "emotion.sad": "sad",
        "emotion.angry": "angry",

        "phase.contact": "contact",
        "phase.passing": "passing",

        "gesture.set": "the whole set",
        "gesture.idle": "idle",
        "gesture.relax": "hand: relaxed",
        "gesture.open": "hand: open",
        "gesture.fist": "hand: fist",
        "gesture.thumbsUp": "thumbs up",
        "gesture.point": "point",
        "gesture.pointHigh": "point, overhead",
        "gesture.present": "present",
        "gesture.guard": "boxing: guard",
        "gesture.jab": "boxing: jab",
        "gesture.cross": "boxing: cross",
        "gesture.work": "working",
        "gesture.reach": "working: reach",

        "action.fight": "boxing",
        "action.use": "working",

        "move.set": "the whole set",
        "move.stance": "stance",
        "move.step": "step",
        "move.guard": "high guard",
        "move.jab": "jab",
        "move.cross": "cross",
        "move.uppercut": "uppercut",
        "move.lowGuard": "low guard",
        "move.sweep": "sweep",
        "move.frontKick": "front kick",
        "move.roundhouse": "roundhouse",
        "move.jumpPunch": "jumping punch",
        "move.jumpKick": "jumping kick",
        "move.knockdown": "knockdown",
        "move.getUp": "get up",

        "pose.relax": "relaxed",
        "pose.open": "open",
        "pose.point": "point",
        "pose.thumbsUp": "thumbs up",
        "pose.fist": "fist",
        "arm.clear": "held clear",
        "arm.point": "raised, bent",
        "arm.high": "high",
        "arm.level": "level",
        "arm.down": "down",

        "face.": "the whole sheet",
        "face.neutral": "neutral",
        "face.happy": "happy",
        "face.sad": "sad",
        "face.angry": "angry",
        "face.disgust": "disgust",
        "face.surprised": "surprised",

        "activity.idle": "nothing",
        "activity.talk": "talks",
        "activity.blink": "blinks",
        "activity.joy": "smiles",
        "activity.anger": "glares",
        "activity.sad": "droops",
        "activity.disgust": "sneers",
        "activity.surprised": "is startled",

        "detail.high": "high",
        "detail.low": "low",
        "detail.minimal": "minimal",
        "detail.auto": "auto",
        "solo.on": "one head",
        "solo.off": "all three",
        "walk.on": "walks",
        "walk.off": "stands",

        "gloves.on": "gloved",
        "gloves.off": "bare",
        "props.on": "the table and the bag",
        "props.off": "an empty room",

        "tier.envelope": "envelope",
        "tier.spectral": "spectral",
        "tier.aligned": "aligned",
        "recording.hello": "hello",
        "recording.sing": "sing",
        "transport.play": "play",
        "transport.stop": "stop",
        "speaker.left": "left",
        "speaker.right": "right",
        "listening.on": "listening",
        "listening.off": "not listening",
        "role.speaker": "speaking",
        "role.listener": "listening",

        "build.player": "player",
        "build.thinker": "thinker",
        "build.eater": "eater",
        "build.hero": "hero",
        "build.child": "child",
        "build.stylized": "stylized",
        "build.thin": "thin",
        "build.neutral": "neutral",
        "build.heavy": "heavy",
        "build.brawny": "brawny",
        "build.bench": "the bench figure",

        "subject.articulated": "articulated hand",
        "subject.plain": "plain hand",

        "read.cycle": "cycle",
        "read.speed": "speed",
        "read.stride": "stride",
        "read.phase": "phase",
        "read.lift": "lift",
        "read.factors": "factors off neutral",
        "read.back": "back curve",
        "read.guardElbow": "guard elbow",
        "read.workElbow": "work elbow",
        "read.workLean": "work lean",
        "read.fistHeight": "fist over shoulder",
        "read.fistReach": "fist reach",
        "read.chin": "fist to chin",
        "read.footHeight": "foot height",
        "read.floor": "lowest foot",
        "read.footHigh": "highest foot",
        "read.posed": "posed",
        "read.distinct": "closest pair",
        "read.mouth": "mouth",
        "read.lips": "lips",
        "read.eyes": "eyes",
        "read.brows": "brows",
        "read.headPx": "head on screen",
        "read.eyePx": "eye on screen",
        "read.boxes": "boxes",
        "read.draws": "draw calls",
        "read.perCharacter": "per character",
        "read.verts": "vertices",
        "read.frameMs": "frame",
        "read.renderMs": "render",
        "read.open": "mouth open",
        "read.open.envelope": "open, envelope",
        "read.open.spectral": "open, spectral",
        "read.open.aligned": "open, aligned",
        "read.got.envelope": "envelope got",
        "read.got.spectral": "spectral got",
        "read.got.aligned": "aligned got",
        "read.wide": "mouth wide",
        "read.round": "mouth round",
        "read.got": "tier used",
        "read.gaze": "gaze",
        "read.nod": "nod",
        "read.brow": "brow",
        "read.palmArm": "palm / arm",
        "read.fingerPx": "index on screen",
        "read.aimOff": "aim off by",
        "read.figurePx": "figure on screen",
        "read.count": "figures",
        "read.speaking": "speaking",

        "unit.headHeights": "head heights",
        "unit.legHeights": "leg heights",
        "unit.arms": "arm lengths"
    },
    "de": {
        "param.frames": "Bilder auf dem Bogen",
        "param.maturity": "Reife",
        "param.femininity": "Weiblichkeit",
        "param.mass": "Masse",
        "param.muscle": "Muskeln",
        "param.intensity": "Intensität",
        "param.workHeight": "Arbeitshöhe",
        "param.count": "Figuren",
        "param.roundness": "Fase an jedem Quader",
        "param.scale": "Figurengröße",
        "param.handScale": "Handgröße",
        "param.handBuild": "Anteil der Hand am Körperbau",

        "choice.base": "Zyklus",
        "choice.preset": "Vorlage",
        "choice.emotion": "Gefühl",
        "choice.gesture": "Spalte",
        "choice.action": "Tätigkeit",
        "choice.move": "Technik",
        "choice.pose": "Handhaltung",
        "choice.arm": "Arm",
        "choice.expression": "Ausdruck",
        "choice.subject": "Gemessen wird",
        "choice.activity": "das Gesicht",
        "choice.detail": "Detail",
        "choice.walking": "die Menge",
        "choice.solo": "gezeigt",
        "choice.recording": "Aufnahme",
        "choice.transport": "Wiedergabe",
        "choice.speaker": "Sprecher",
        "choice.listening": "der andere",
        "choice.build": "Körperbau",
        "choice.gloves": "Hände",
        "choice.props": "Requisiten",

        "base.walk": "Gehen",
        "base.run": "Laufen",

        "preset.": "keine",
        "preset.neutral": "neutral",
        "preset.cheerful": "fröhlich",
        "preset.dejected": "niedergeschlagen",
        "preset.furious": "wütend",
        "preset.elderly": "betagt",
        "preset.toddler": "Kleinkind",
        "preset.heavy": "schwer",
        "preset.sneak": "schleichend",
        "preset.proud": "stolz",
        "preset.march": "Marsch",

        "emotion.": "keins",
        "emotion.happy": "froh",
        "emotion.sad": "traurig",
        "emotion.angry": "zornig",

        "phase.contact": "Kontakt",
        "phase.passing": "Durchgang",

        "gesture.set": "der ganze Satz",
        "gesture.idle": "Ruhe",
        "gesture.relax": "Hand: locker",
        "gesture.open": "Hand: offen",
        "gesture.fist": "Hand: Faust",
        "gesture.thumbsUp": "Daumen hoch",
        "gesture.point": "zeigen",
        "gesture.pointHigh": "zeigen, über Kopf",
        "gesture.present": "vorzeigen",
        "gesture.guard": "Boxen: Deckung",
        "gesture.jab": "Boxen: Jab",
        "gesture.cross": "Boxen: Cross",
        "gesture.work": "arbeiten",
        "gesture.reach": "arbeiten: greifen",

        "action.fight": "Boxen",
        "action.use": "Arbeiten",

        "move.set": "der ganze Satz",
        "move.stance": "Stand",
        "move.step": "Schritt",
        "move.guard": "hohe Deckung",
        "move.jab": "Jab",
        "move.cross": "Cross",
        "move.uppercut": "Aufwärtshaken",
        "move.lowGuard": "tiefe Deckung",
        "move.sweep": "Fegen",
        "move.frontKick": "Fronttritt",
        "move.roundhouse": "Roundhouse",
        "move.jumpPunch": "Sprungschlag",
        "move.jumpKick": "Sprungtritt",
        "move.knockdown": "Niederschlag",
        "move.getUp": "Aufstehen",

        "pose.relax": "locker",
        "pose.open": "offen",
        "pose.point": "zeigen",
        "pose.thumbsUp": "Daumen hoch",
        "pose.fist": "Faust",
        "arm.clear": "frei gehalten",
        "arm.point": "gehoben, gebeugt",
        "arm.high": "hoch",
        "arm.level": "waagerecht",
        "arm.down": "unten",

        "face.": "der ganze Bogen",
        "face.neutral": "neutral",
        "face.happy": "froh",
        "face.sad": "traurig",
        "face.angry": "zornig",
        "face.disgust": "Ekel",
        "face.surprised": "überrascht",

        "activity.idle": "nichts",
        "activity.talk": "spricht",
        "activity.blink": "blinzelt",
        "activity.joy": "lächelt",
        "activity.anger": "starrt zornig",
        "activity.sad": "lässt sich hängen",
        "activity.disgust": "verzieht das Gesicht",
        "activity.surprised": "erschrickt",

        "detail.high": "hoch",
        "detail.low": "niedrig",
        "detail.minimal": "minimal",
        "detail.auto": "automatisch",
        "solo.on": "ein Kopf",
        "solo.off": "alle drei",
        "walk.on": "geht",
        "walk.off": "steht",

        "gloves.on": "mit Handschuh",
        "gloves.off": "bloß",
        "props.on": "Tisch und Sack",
        "props.off": "leerer Raum",

        "tier.envelope": "Hüllkurve",
        "tier.spectral": "spektral",
        "tier.aligned": "ausgerichtet",
        "recording.hello": "hello",
        "recording.sing": "sing",
        "transport.play": "abspielen",
        "transport.stop": "anhalten",
        "speaker.left": "links",
        "speaker.right": "rechts",
        "listening.on": "hört zu",
        "listening.off": "hört nicht zu",
        "role.speaker": "spricht",
        "role.listener": "hört zu",

        "build.player": "Spieler",
        "build.thinker": "Denker",
        "build.eater": "Esser",
        "build.hero": "Held",
        "build.child": "Kind",
        "build.stylized": "stilisiert",
        "build.thin": "dünn",
        "build.neutral": "neutral",
        "build.heavy": "schwer",
        "build.brawny": "kräftig",
        "build.bench": "die Bankfigur",

        "subject.articulated": "gegliederte Hand",
        "subject.plain": "einfache Hand",

        "read.cycle": "Zyklus",
        "read.speed": "Tempo",
        "read.stride": "Schrittlänge",
        "read.phase": "Phase",
        "read.lift": "Hub",
        "read.factors": "Faktoren neben neutral",
        "read.back": "Rückenkrümmung",
        "read.guardElbow": "Ellbogen in Deckung",
        "read.workElbow": "Ellbogen bei der Arbeit",
        "read.workLean": "Neigung bei der Arbeit",
        "read.fistHeight": "Faust über Schulter",
        "read.fistReach": "Faustreichweite",
        "read.chin": "Faust zum Kinn",
        "read.footHeight": "Fußhöhe",
        "read.floor": "tiefster Fuß",
        "read.footHigh": "höchster Fuß",
        "read.posed": "gestellt",
        "read.distinct": "engstes Paar",
        "read.mouth": "Mund",
        "read.lips": "Lippen",
        "read.eyes": "Augen",
        "read.brows": "Brauen",
        "read.headPx": "Kopf am Bildschirm",
        "read.eyePx": "Auge am Bildschirm",
        "read.boxes": "Quader",
        "read.draws": "Zeichenaufrufe",
        "read.perCharacter": "je Figur",
        "read.verts": "Eckpunkte",
        "read.frameMs": "Bild",
        "read.renderMs": "Rendern",
        "read.open": "Mund offen",
        "read.open.envelope": "offen, Hüllkurve",
        "read.open.spectral": "offen, spektral",
        "read.open.aligned": "offen, ausgerichtet",
        "read.got.envelope": "Hüllkurve nutzt",
        "read.got.spectral": "spektral nutzt",
        "read.got.aligned": "ausgerichtet nutzt",
        "read.wide": "Mund breit",
        "read.round": "Mund rund",
        "read.got": "verwendete Stufe",
        "read.gaze": "Blick",
        "read.nod": "Nicken",
        "read.brow": "Braue",
        "read.palmArm": "Handfläche / Arm",
        "read.fingerPx": "Zeigefinger am Bildschirm",
        "read.aimOff": "Zielfehler",
        "read.figurePx": "Figur am Bildschirm",
        "read.count": "Figuren",
        "read.speaking": "spricht",

        "unit.headHeights": "Kopfhöhen",
        "unit.legHeights": "Beinlängen",
        "unit.arms": "Armlängen"
    }
}
