# (c) Clayground Contributors - MIT License, see "LICENSE" file

# Build one shader out of several .glsl parts.
#
#   clay_compose_shader(box3d.frag
#       PARTS box3d_edges.glsl box3d_main.glsl box3d_toon.glsl)
#
# GLSL has no #include and Qt's shader tooling adds none, so a fragment shader
# that has to behave like another one - a body part lit like every other body
# part, outlined at the same weight - would otherwise have to carry a copy of
# it. Copies of a shader drift, and a shader that has drifted looks like a
# different material rather than like a bug.
#
# Parts are concatenated in the order given, so anything a part calls must
# appear in a part before it. A part declares no VARYINGs of its own and takes
# what it needs as function parameters, which is what lets it sit ahead of the
# host shader's own declarations.
#
# The output lands in the current binary dir and the caller passes THAT path to
# clay_plugin(RESOURCES ...). It is written at configure time rather than by a
# build rule because qt_add_qml_module has to see the file when it runs; the
# parts are added to CMAKE_CONFIGURE_DEPENDS so that editing one re-runs cmake,
# and configure_file(COPYONLY) leaves the timestamp alone when the composed text
# has not actually changed, so an unrelated reconfigure does not rebuild the
# world.
#
# Sets <name>_SHADER in the caller's scope to the absolute output path.
function(clay_compose_shader OUT_NAME)
    cmake_parse_arguments(CLAY_SHADER "" "" "PARTS" ${ARGN})

    if(NOT CLAY_SHADER_PARTS)
        message(FATAL_ERROR "clay_compose_shader(${OUT_NAME}): no PARTS given")
    endif()

    set(_text "// GENERATED by clay_compose_shader() - do not edit.\n")
    string(APPEND _text "// Composed from: ${CLAY_SHADER_PARTS}\n")
    string(APPEND _text "// Edit those parts instead; this file is overwritten on every configure.\n\n")

    foreach(_part ${CLAY_SHADER_PARTS})
        get_filename_component(_abs "${_part}" ABSOLUTE)
        if(NOT EXISTS "${_abs}")
            message(FATAL_ERROR "clay_compose_shader(${OUT_NAME}): missing part ${_abs}")
        endif()
        file(READ "${_abs}" _chunk)
        get_filename_component(_leaf "${_abs}" NAME)
        string(APPEND _text "// ---- ${_leaf} ----\n${_chunk}\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_abs}")
    endforeach()

    set(_out "${CMAKE_CURRENT_BINARY_DIR}/${OUT_NAME}")
    set(_stage "${CMAKE_CURRENT_BINARY_DIR}/${OUT_NAME}.stage")
    file(WRITE "${_stage}" "${_text}")
    configure_file("${_stage}" "${_out}" COPYONLY)

    # The composed file lives in the build tree, so Qt would otherwise refuse
    # it: a resource entry needs a path relative to the source dir to derive
    # its URL from, and an absolute one has none. Aliasing it to its bare name
    # puts it in the resource system exactly where a hand-written shader of the
    # same name would have been, which is what `fragmentShader: "box3d.frag"`
    # in the QML resolves against.
    set_source_files_properties("${_out}" PROPERTIES
        GENERATED TRUE
        QT_RESOURCE_ALIAS "${OUT_NAME}")

    get_filename_component(_var "${OUT_NAME}" NAME_WE)
    set(${_var}_SHADER "${_out}" PARENT_SCOPE)
endfunction()
